import '@fontsource/montserrat/300.css'
import '@fontsource/montserrat/400.css'
import '@fontsource/montserrat/700.css'
import '@fontsource/source-code-pro'
import '@fontsource/rubik'
import './src/css/global.css'
